### ISSUE TITLE
Can't add AWS Route 53

### ISSUE THREAD

**Issue by jzohrab** [adammeghji/terraform-demo#2]
The demo currently fails (after PR #1 is accepted) when adding DNS entries: 

`aws_route53_record.tfdemo: AccessDenied: User: arn:aws:iam::603897991439:user/jzohrab is not authorized to access this resource ... status code: 403, request id: da6ed40b-9565-11e5-a494-6f4148c92156`.  I'm assuming this has something to do with universe.com owning that DNS zone/domain.

What's a good solution here?  Having users create their own domains, and then have them test that?  Bit of a drag as domains cost enough money to be a hassle.  Would a better solution be to split this portion off into a separate terraform file somehow?  I'm not sure how that would work given the Terraform variable interpolations that are happening (eg  `name = "${aws_elb.frontend.dns_name}"`).

**Comment by adammeghji** [comment]
In a real use case, you'd want to add a resource, a-la:

```
resource "aws_route53_zone" "primary" {
   name = "universe.com"
}
```

That breaks the demo :)  so, instead, you can add something like this to `base.tf`:

```
variable "zone_id" {
  default = "ZT0C35LV57KL2"
}
```

then:

```
resource "aws_route53_record" "tfdemo" {
  zone_id = "${var.zone_id}"
  ...
}
```

**Comment by adammeghji** [comment]
This should do the trick: https://github.com/adammeghji/terraform-demo/commit/1d306dfde657d25480162d3b0455b50db855a7bc
